name: checkrail
version: 0.1.0.0
github: tonicebrian/checkrail
license: Apache-2.0
author: Toni Cebrián
maintainer: toni@tonicebrian.com

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/tonicebrian/backend#readme>

dependencies:
  - aeson
  - base
  - either
  - filepath
  - insert-ordered-containers
  - lens
  - mtl
  - optparse-simple
  - openapi3
  - pretty-simple
  - shakespeare
  - text
  - yaml

default-extensions:
  # Recommended by RIO
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  # This is controversial but I'm using it because
  - -fno-warn-orphans

library:
  source-dirs: src

executables:
  checkrail-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - checkrail
      - optparse-simple
      - pretty-simple
      - text

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  checkrail-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - checkrail
      - sydtest
      - sydtest-discover

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
